import { palette } from '../palettes/alabaster-dark';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Alabaster Dark',
  uiTheme: 'vs-dark',
  colors: {
    'activityBar.background': palette.gray1,
    'button.background': palette.accent,
    'list.highlightForeground': palette.accent,
    'textLink.foreground': palette.accent,
    'textLink.activeForeground': palette.accent,
    'focusBorder': palette.accent + '80',
    'settings.focusedRowBorder': palette.accent,
    'settings.modifiedItemIndicator': palette.accent,
    'textPreformat.foreground': palette.string,
    'editor.background': palette.gray2,
    'editor.foreground': palette.gray7,
    'editorIndentGuide.background1': palette.gray4 + '80',
    'editorLineNumber.activeForeground': palette.gray7,
    'editorLineNumber.foreground': palette.gray5,
    'editorGroupHeader.border': palette.gray4,
    'editorGroupHeader.tabsBorder': palette.gray4,
    'editorGroupHeader.tabsBackground': palette.gray1,
    'list.activeSelectionBackground': palette.gray4,
    'list.activeSelectionForeground': palette.gray7,
    'list.activeSelectionIconForeground': '#fff',
    'panel.border': palette.gray4,
    'sideBar.background': palette.gray1,
    'sideBar.border': palette.gray4,
    'sideBarSectionHeader.background': palette.gray1,
    'sideBarSectionHeader.foreground': palette.gray7,
    'statusBar.background': palette.gray1,
    'statusBar.border': palette.gray4,
    'statusBar.foreground': palette.gray7,
    'tab.activeBackground': palette.gray2,
    'tab.activeBorder': palette.gray2,
    'tab.activeBorderTop': palette.accent,
    'tab.border': palette.gray4,
    'tab.inactiveBackground': palette.gray1,
    'tab.inactiveForeground': palette.gray6,
    'titleBar.border': palette.gray4,
    'titleBar.activeBackground': palette.gray1,
    'titleBar.activeForeground': palette.gray7,
    'titleBar.inactiveBackground': palette.gray1,
    'titleBar.inactiveForeground': palette.gray6,
    'terminal.ansiBlack': palette.black,
    'terminal.ansiRed': palette.red,
    'terminal.ansiGreen': palette.green,
    'terminal.ansiYellow': palette.yellow,
    'terminal.ansiBlue': palette.blue,
    'terminal.ansiMagenta': palette.magenta,
    'terminal.ansiCyan': palette.cyan,
    'terminal.ansiWhite': palette.white,
    'terminal.ansiBrightBlack': palette.blackBright,
    'terminal.ansiBrightRed': palette.redBright,
    'terminal.ansiBrightGreen': palette.greenBright,
    'terminal.ansiBrightYellow': palette.yellowBright,
    'terminal.ansiBrightBlue': palette.blueBright,
    'terminal.ansiBrightMagenta': palette.magentaBright,
    'terminal.ansiBrightCyan': palette.cyanBright,
    'terminal.ansiBrightWhite': palette.whiteBright,
    'terminal.foreground': palette.gray7,
  },
  tokenColors: [
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.comment },
    },
    {
      name: 'Strings',
      scope: ['string', 'punctuation.definition.string'],
      settings: { foreground: palette.string },
    },
    {
      name: 'Constants',
      scope: ['constant', 'punctuation.definition.constant', 'support.constant', 'variable.language'],
      settings: { foreground: palette.constant },
    },
    {
      name: 'Definitions',
      scope: ['entity.name.function', 'entity.name.type', 'entity.name.class', 'entity.name.struct', 'support.function', 'support.class'],
      settings: { foreground: palette.definition },
    },
    {
      name: 'Punctuation',
      scope: ['punctuation', 'keyword.operator'],
      settings: { foreground: palette.punctuation },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.definition },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.string, fontStyle: '' },
    },
  ],
};
