import { palette } from '../palettes/atom-one-light';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Atom One Light',
  uiTheme: 'vs',
  colors: {
    'activityBar.background': palette.gray1,
    'button.background': palette.blue,
    'list.highlightForeground': palette.blue,
    'textLink.foreground': palette.blue,
    'textLink.activeForeground': palette.blue,
    'focusBorder': palette.blue + '80',
    'settings.focusedRowBorder': palette.blue,
    'settings.modifiedItemIndicator': palette.blue,
    'textPreformat.foreground': palette.red,
    'editor.background': palette.gray8,
    'editor.foreground': palette.gray2,
    'editorIndentGuide.background1': palette.gray2 + '1F',
    'editorLineNumber.activeForeground': palette.gray2,
    'editorLineNumber.foreground': palette.gray4,
    'editorGroupHeader.border': palette.gray5,
    'editorGroupHeader.tabsBorder': palette.gray5,
    'editorGroupHeader.tabsBackground': palette.gray6,
    'list.activeSelectionBackground': palette.gray5,
    'list.activeSelectionForeground': palette.gray2,
    'list.activeSelectionIconForeground': palette.gray2,
    'sideBar.background': palette.gray8,
    'sideBar.border': palette.gray5,
    'sideBarSectionHeader.background': palette.gray7,
    'sideBarSectionHeader.foreground': palette.gray2,
    'panel.border': palette.gray5,
    'statusBar.background': palette.gray8,
    'statusBar.border': palette.gray5,
    'statusBar.foreground': palette.gray2,
    'tab.activeBackground': palette.gray8,
    'tab.activeBorder': palette.gray8,
    'tab.activeBorderTop': palette.blue,
    'tab.border': palette.gray5,
    'tab.inactiveBackground': palette.gray6,
    'tab.inactiveForeground': palette.gray3,
    'titleBar.border': palette.gray5,
    'titleBar.activeBackground': palette.gray6,
    'titleBar.activeForeground': palette.gray2,
    'titleBar.inactiveBackground': palette.gray6,
    'titleBar.inactiveForeground': palette.gray2,
    'terminal.ansiBlack': palette.gray2,
    'terminal.ansiRed': palette.red,
    'terminal.ansiGreen': palette.green,
    'terminal.ansiYellow': palette.darkAmber,
    'terminal.ansiBlue': palette.blue,
    'terminal.ansiMagenta': palette.purple,
    'terminal.ansiCyan': palette.teal,
    'terminal.ansiWhite': palette.gray7,
    'terminal.ansiBrightBlack': palette.gray3,
    'terminal.ansiBrightRed': palette.red,
    'terminal.ansiBrightGreen': palette.green,
    'terminal.ansiBrightYellow': palette.amber,
    'terminal.ansiBrightBlue': palette.blue,
    'terminal.ansiBrightMagenta': palette.purple,
    'terminal.ansiBrightCyan': palette.teal,
    'terminal.ansiBrightWhite': palette.gray8,
    'terminal.foreground': palette.gray2,
  },
  tokenColors: [
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.mono3 },
    },
    {
      name: 'Comments: Documentation',
      scope: ['comment.documentation', 'comment.block.documentation'],
      settings: { foreground: palette.mono3 },
    },
    {
      name: 'Operators',
      scope: 'keyword.operator',
      settings: { foreground: palette.teal },
    },
    {
      name: 'Keywords',
      scope: ['keyword', 'storage', 'storage.type.builtin', 'storage.type.modifier'],
      settings: { foreground: palette.purple },
    },
    {
      name: 'Language Constants',
      scope: ['constant.language', 'support.constant', 'variable.language'],
      settings: { foreground: palette.darkAmber },
    },
    {
      name: 'Variable - Property',
      scope: ['variable.other.property', 'variable.other.object.property'],
      settings: { foreground: palette.red },
    },
    {
      name: 'Functions',
      scope: ['entity.name.function', 'support.function'],
      settings: { foreground: palette.blue },
    },
    {
      name: 'Classes',
      scope: ['entity.name.type', 'entity.other.inherited-class', 'support.class'],
      settings: { foreground: palette.amber },
    },
    {
      name: 'Numbers, Characters',
      scope: ['constant.numeric', 'constant.character', 'constant'],
      settings: { foreground: palette.darkAmber },
    },
    {
      name: 'Strings',
      scope: 'string',
      settings: { foreground: palette.green },
    },
    {
      name: 'Strings: Symbols',
      scope: 'constant.other.symbol',
      settings: { foreground: palette.red },
    },
    {
      name: 'CSS: Property Names',
      scope: ['meta.property-name', 'support.type.property-name'],
      settings: { foreground: palette.red },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.red },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.darkAmber, fontStyle: '' },
    },
  ],
};
