import { palette } from '../palettes/catppuccin-mocha';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Catppuccin Mocha',
  uiTheme: 'vs-dark',
  colors: {
    'activityBar.background': palette.gray1,
    'button.background': palette.mauve,
    'button.foreground': palette.gray2,
    'button.hoverBackground': palette.mauve + 'E6',
    'list.highlightForeground': palette.mauve,
    'textLink.foreground': palette.mauve,
    'textLink.activeForeground': palette.mauve,
    'focusBorder': palette.mauve + '80',
    'settings.focusedRowBorder': palette.mauve,
    'settings.modifiedItemIndicator': palette.mauve,
    'textPreformat.foreground': palette.peach,
    'editor.background': palette.gray2,
    'editor.foreground': palette.gray7,
    'editorIndentGuide.background1': palette.gray4 + '80',
    'editorLineNumber.activeForeground': palette.gray7,
    'editorLineNumber.foreground': palette.gray5,
    'editorGroupHeader.border': palette.gray4,
    'editorGroupHeader.tabsBorder': palette.gray4,
    'editorGroupHeader.tabsBackground': palette.gray1,
    'list.activeSelectionBackground': palette.gray4,
    'list.activeSelectionForeground': palette.gray7,
    'list.activeSelectionIconForeground': '#fff',
    'panel.border': palette.gray4,
    'sideBar.background': palette.gray1,
    'sideBar.border': palette.gray4,
    'sideBarSectionHeader.background': palette.gray1,
    'sideBarSectionHeader.foreground': palette.gray7,
    'statusBar.background': palette.gray1,
    'statusBar.border': palette.gray4,
    'statusBar.foreground': palette.gray7,
    'tab.activeBackground': palette.gray2,
    'tab.activeBorder': palette.gray2,
    'tab.activeBorderTop': palette.mauve,
    'tab.border': palette.gray4,
    'tab.inactiveBackground': palette.gray1,
    'tab.inactiveForeground': palette.gray6,
    'titleBar.border': palette.gray4,
    'titleBar.activeBackground': palette.gray1,
    'titleBar.activeForeground': palette.gray7,
    'titleBar.inactiveBackground': palette.gray1,
    'titleBar.inactiveForeground': palette.gray6,
    'terminal.ansiBlack': palette.gray2,
    'terminal.ansiRed': palette.red,
    'terminal.ansiGreen': palette.green,
    'terminal.ansiYellow': palette.yellow,
    'terminal.ansiBlue': palette.blue,
    'terminal.ansiMagenta': palette.mauve,
    'terminal.ansiCyan': palette.teal,
    'terminal.ansiWhite': palette.gray7,
    'terminal.ansiBrightBlack': palette.gray5,
    'terminal.ansiBrightRed': palette.red,
    'terminal.ansiBrightGreen': palette.green,
    'terminal.ansiBrightYellow': palette.yellow,
    'terminal.ansiBrightBlue': palette.blue,
    'terminal.ansiBrightMagenta': palette.pink,
    'terminal.ansiBrightCyan': palette.sky,
    'terminal.ansiBrightWhite': palette.rosewater,
    'terminal.foreground': palette.gray7,
  },
  tokenColors: [
    {
      name: 'Basic text & variable names',
      scope: ['text', 'source', 'variable.other.readwrite', 'punctuation.definition.variable'],
      settings: { foreground: palette.gray7 },
    },
    {
      name: 'Punctuation',
      scope: 'punctuation',
      settings: { foreground: palette.overlay2 },
    },
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.gray6 },
    },
    {
      name: 'Strings',
      scope: ['string', 'punctuation.definition.string'],
      settings: { foreground: palette.green },
    },
    {
      name: 'Escape sequences',
      scope: 'constant.character.escape',
      settings: { foreground: palette.pink },
    },
    {
      name: 'Booleans, constants, numbers',
      scope: [
        'constant.numeric',
        'variable.other.constant',
        'entity.name.constant',
        'constant.language.boolean',
        'constant.language.false',
        'constant.language.true',
        'keyword.other.unit.user-defined',
        'keyword.other.unit.suffix.floating-point',
      ],
      settings: { foreground: palette.peach },
    },
    {
      name: 'Keywords',
      scope: [
        'keyword',
        'keyword.operator.word',
        'keyword.operator.new',
        'variable.language.super',
        'support.type.primitive',
        'storage.type',
        'storage.modifier',
        'punctuation.definition.keyword',
      ],
      settings: { foreground: palette.mauve },
    },
    {
      name: 'Operators',
      scope: [
        'keyword.operator',
        'punctuation.accessor',
        'punctuation.definition.generic',
        'punctuation.definition.tag',
        'punctuation.separator.key-value',
      ],
      settings: { foreground: palette.teal },
    },
    {
      name: 'Functions',
      scope: [
        'entity.name.function',
        'meta.function-call.method',
        'support.function',
        'support.function.misc',
        'variable.function',
      ],
      settings: { foreground: palette.blue },
    },
    {
      name: 'Classes',
      scope: [
        'entity.name.class',
        'entity.other.inherited-class',
        'support.class',
        'meta.function-call.constructor',
        'entity.name.struct',
      ],
      settings: { foreground: palette.yellow },
    },
    {
      name: 'Types',
      scope: ['meta.type', 'meta.type-alias', 'support.type', 'entity.name.type'],
      settings: { foreground: palette.yellow },
    },
    {
      name: 'Enum members',
      scope: ['meta.enum variable.other.readwrite', 'variable.other.enummember'],
      settings: { foreground: palette.teal },
    },
    {
      name: 'Parameters',
      scope: ['variable.parameter', 'meta.function.parameters'],
      settings: { foreground: palette.maroon },
    },
    {
      name: 'Built-ins',
      scope: ['constant.language', 'support.function.builtin'],
      settings: { foreground: palette.red },
    },
    {
      name: 'This/Self',
      scope: ['variable.language.this', 'variable.language.this punctuation.definition.variable'],
      settings: { foreground: palette.red },
    },
    {
      name: 'Decorators',
      scope: [
        'meta.annotation variable.function',
        'meta.annotation variable.annotation.function',
        'meta.annotation punctuation.definition.annotation',
        'meta.decorator',
        'punctuation.decorator',
      ],
      settings: { foreground: palette.peach },
    },
    {
      name: 'Object properties',
      scope: ['variable.object.property', 'meta.property.object'],
      settings: { foreground: palette.gray7 },
    },
    {
      name: 'String interpolation',
      scope: ['string.template variable', 'string variable'],
      settings: { foreground: palette.gray7 },
    },
    {
      name: 'CSS: Property Names',
      scope: ['support.type.property-name.css', 'support.type.property-name.less'],
      settings: { foreground: palette.blue },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.red },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { foreground: palette.peach, fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.rosewater, fontStyle: '' },
    },
  ],
};
