import { palette } from '../palettes/dracula-plus';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Dracula Plus',
  uiTheme: 'vs-dark',
  colors: {
    'activityBar.background': palette.gray1,
    'button.background': palette.purple,
    'button.foreground': palette.gray2,
    'button.hoverBackground': palette.purple + 'E6',
    'list.highlightForeground': palette.purple,
    'textLink.foreground': palette.purple,
    'textLink.activeForeground': palette.purple,
    'focusBorder': palette.purple + '80',
    'settings.focusedRowBorder': palette.purple,
    'settings.modifiedItemIndicator': palette.purple,
    'textPreformat.foreground': palette.pink,
    'editor.background': palette.gray2,
    'editor.foreground': palette.white,
    'editorIndentGuide.background1': palette.gray4 + '80',
    'editorLineNumber.activeForeground': palette.white,
    'editorLineNumber.foreground': palette.gray6,
    'editorGroupHeader.border': palette.gray4,
    'editorGroupHeader.tabsBorder': palette.gray4,
    'editorGroupHeader.tabsBackground': palette.gray1,
    'list.activeSelectionBackground': palette.gray4,
    'list.activeSelectionForeground': palette.gray7,
    'list.activeSelectionIconForeground': '#fff',
    'panel.border': palette.gray4,
    'sideBar.background': palette.gray1,
    'sideBar.border': palette.gray4,
    'sideBarSectionHeader.background': palette.gray1,
    'sideBarSectionHeader.foreground': palette.white,
    'statusBar.background': palette.gray1,
    'statusBar.border': palette.gray4,
    'statusBar.foreground': palette.white,
    'tab.activeBackground': palette.gray2,
    'tab.activeBorder': palette.gray2,
    'tab.activeBorderTop': palette.purple,
    'tab.border': palette.gray4,
    'tab.inactiveBackground': palette.gray1,
    'tab.inactiveForeground': palette.gray6,
    'titleBar.border': palette.gray4,
    'titleBar.activeBackground': palette.gray1,
    'titleBar.activeForeground': palette.white,
    'titleBar.inactiveBackground': palette.gray1,
    'titleBar.inactiveForeground': palette.gray6,
    'terminal.ansiBlack': palette.black,
    'terminal.ansiRed': palette.red,
    'terminal.ansiGreen': palette.green,
    'terminal.ansiYellow': palette.yellow,
    'terminal.ansiBlue': palette.blue,
    'terminal.ansiMagenta': palette.magenta,
    'terminal.ansiCyan': palette.cyan,
    'terminal.ansiWhite': palette.white,
    'terminal.ansiBrightBlack': palette.blackBright,
    'terminal.ansiBrightRed': palette.redBright,
    'terminal.ansiBrightGreen': palette.greenBright,
    'terminal.ansiBrightYellow': palette.yellowBright,
    'terminal.ansiBrightBlue': palette.blueBright,
    'terminal.ansiBrightMagenta': palette.magentaBright,
    'terminal.ansiBrightCyan': palette.cyanBright,
    'terminal.ansiBrightWhite': palette.whiteBright,
    'terminal.foreground': palette.white,
  },
  tokenColors: [
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.gray6, fontStyle: 'italic' },
    },
    {
      name: 'Comments: Documentation',
      scope: ['comment.documentation', 'comment.block.documentation'],
      settings: { foreground: palette.gray6 },
    },
    {
      name: 'Operators',
      scope: 'keyword.operator',
      settings: { foreground: palette.pink },
    },
    {
      name: 'Keywords',
      scope: ['keyword', 'storage', 'storage.type.builtin', 'storage.type.modifier'],
      settings: { foreground: palette.pink },
    },
    {
      name: 'Language Constants',
      scope: ['constant.language', 'support.constant', 'variable.language'],
      settings: { foreground: palette.purple },
    },
    {
      name: 'Variable - Property',
      scope: ['variable.other.property', 'variable.other.object.property'],
      settings: { foreground: palette.white },
    },
    {
      name: 'Functions',
      scope: ['entity.name.function', 'support.function'],
      settings: { foreground: palette.green },
    },
    {
      name: 'Classes',
      scope: ['entity.name.type', 'entity.other.inherited-class', 'support.class'],
      settings: { foreground: palette.cyan },
    },
    {
      name: 'Numbers, Characters',
      scope: ['constant.numeric', 'constant.character', 'constant'],
      settings: { foreground: palette.purple },
    },
    {
      name: 'Strings',
      scope: 'string',
      settings: { foreground: palette.yellow },
    },
    {
      name: 'Strings: Symbols',
      scope: 'constant.other.symbol',
      settings: { foreground: palette.orange },
    },
    {
      name: 'CSS: Property Names',
      scope: ['meta.property-name', 'support.type.property-name'],
      settings: { foreground: palette.cyan },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.purple },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { foreground: palette.orange, fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.orange, fontStyle: '' },
    },
  ],
};
