import { palette } from '../palettes/tango-dark';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Tango Dark',
  uiTheme: 'vs-dark',
  colors: {
    'activityBar.background': palette.gray1,
    'button.background': palette.blue,
    'list.highlightForeground': palette.blueBright,
    'textLink.foreground': palette.blueBright,
    'textLink.activeForeground': palette.blueBright,
    'focusBorder': palette.blueBright + '80',
    'settings.focusedRowBorder': palette.blueBright,
    'settings.modifiedItemIndicator': palette.blueBright,
    'textPreformat.foreground': palette.greenBright,
    'editor.background': palette.gray2,
    'editor.foreground': palette.gray7,
    'editorIndentGuide.background1': palette.gray4 + '80',
    'editorLineNumber.activeForeground': palette.gray7,
    'editorLineNumber.foreground': palette.gray5,
    'editorGroupHeader.border': palette.gray4,
    'editorGroupHeader.tabsBorder': palette.gray4,
    'editorGroupHeader.tabsBackground': palette.gray1,
    'list.activeSelectionBackground': palette.gray4,
    'list.activeSelectionForeground': palette.gray7,
    'list.activeSelectionIconForeground': '#fff',
    'panel.border': palette.gray4,
    'sideBar.background': palette.gray1,
    'sideBar.border': palette.gray4,
    'sideBarSectionHeader.background': palette.gray1,
    'sideBarSectionHeader.foreground': palette.gray7,
    'statusBar.background': palette.gray1,
    'statusBar.border': palette.gray4,
    'statusBar.foreground': palette.gray7,
    'tab.activeBackground': palette.gray2,
    'tab.activeBorder': palette.gray2,
    'tab.activeBorderTop': palette.blueBright,
    'tab.border': palette.gray4,
    'tab.inactiveBackground': palette.gray1,
    'tab.inactiveForeground': palette.gray6,
    'titleBar.border': palette.gray4,
    'titleBar.activeBackground': palette.gray1,
    'titleBar.activeForeground': palette.gray7,
    'titleBar.inactiveBackground': palette.gray1,
    'titleBar.inactiveForeground': palette.gray6,
    'terminal.ansiBlack': palette.black,
    'terminal.ansiRed': palette.red,
    'terminal.ansiGreen': palette.green,
    'terminal.ansiYellow': palette.yellow,
    'terminal.ansiBlue': palette.blue,
    'terminal.ansiMagenta': palette.magenta,
    'terminal.ansiCyan': palette.cyan,
    'terminal.ansiWhite': palette.white,
    'terminal.ansiBrightBlack': palette.blackBright,
    'terminal.ansiBrightRed': palette.redBright,
    'terminal.ansiBrightGreen': palette.greenBright,
    'terminal.ansiBrightYellow': palette.yellowBright,
    'terminal.ansiBrightBlue': palette.blueBright,
    'terminal.ansiBrightMagenta': palette.magentaBright,
    'terminal.ansiBrightCyan': palette.cyanBright,
    'terminal.ansiBrightWhite': palette.whiteBright,
    'terminal.foreground': palette.gray7,
  },
  tokenColors: [
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.blackBright },
    },
    {
      name: 'Strings',
      scope: ['string', 'punctuation.definition.string'],
      settings: { foreground: palette.greenBright },
    },
    {
      name: 'Escape sequences',
      scope: 'constant.character.escape',
      settings: { foreground: palette.cyanBright },
    },
    {
      name: 'Constants',
      scope: ['constant', 'constant.numeric', 'constant.language', 'support.constant', 'variable.language'],
      settings: { foreground: palette.cyanBright },
    },
    {
      name: 'Keywords',
      scope: ['keyword', 'storage', 'storage.type', 'storage.modifier'],
      settings: { foreground: palette.magentaBright },
    },
    {
      name: 'Operators',
      scope: 'keyword.operator',
      settings: { foreground: palette.gray7 },
    },
    {
      name: 'Functions',
      scope: ['entity.name.function', 'support.function', 'variable.function', 'meta.function-call.method'],
      settings: { foreground: palette.blueBright },
    },
    {
      name: 'Classes & Types',
      scope: ['entity.name.type', 'entity.name.class', 'entity.other.inherited-class', 'support.class', 'support.type', 'meta.type', 'meta.type-alias'],
      settings: { foreground: palette.yellowBright },
    },
    {
      name: 'Parameters',
      scope: ['variable.parameter', 'meta.function.parameters'],
      settings: { foreground: palette.white },
    },
    {
      name: 'Properties',
      scope: ['variable.other.property', 'variable.other.object.property'],
      settings: { foreground: palette.gray7 },
    },
    {
      name: 'Punctuation',
      scope: 'punctuation',
      settings: { foreground: palette.gray6 },
    },
    {
      name: 'Tags (HTML/JSX)',
      scope: 'entity.name.tag',
      settings: { foreground: palette.redBright },
    },
    {
      name: 'Tag attributes',
      scope: 'entity.other.attribute-name',
      settings: { foreground: palette.yellowBright },
    },
    {
      name: 'CSS: Property Names',
      scope: ['support.type.property-name.css', 'support.type.property-name.less'],
      settings: { foreground: palette.blueBright },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.blueBright },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.greenBright, fontStyle: '' },
    },
  ],
};
