import { palette } from '../palettes/xcode-default-light';
import type { ThemeDefinition } from '../lib/types';

export const theme: ThemeDefinition = {
  name: 'Canonical - Xcode Default Light',
  uiTheme: 'vs',
  colors: {
    'activityBar.background': palette.uiBackground,
    'button.background': palette.uiAccent,
    'list.highlightForeground': palette.uiAccent,
    'textLink.foreground': palette.uiAccent,
    'textLink.activeForeground': palette.uiAccent,
    'focusBorder': palette.uiAccent + '80',
    'settings.focusedRowBorder': palette.uiAccent,
    'settings.modifiedItemIndicator': palette.uiAccent,
    'textPreformat.foreground': palette.preprocessorStatements,
    'editor.background': palette.editorBackground,
    'editor.foreground': palette.plainText,
    'editor.selectionBackground': palette.editorSelection,
    'editor.lineHighlightBackground': palette.editorCurrentLine,
    'editorCursor.foreground': palette.editorCursor,
    'editorWhitespace.foreground': palette.editorInvisibles,
    'editorIndentGuide.background1': palette.editorInvisibles,
    'editorLineNumber.activeForeground': palette.uiForeground,
    'editorLineNumber.foreground': palette.uiForegroundDim,
    'editorGroupHeader.border': palette.uiBorder,
    'editorGroupHeader.tabsBorder': palette.uiBorder,
    'editorGroupHeader.tabsBackground': palette.uiBackground,
    'list.activeSelectionBackground': palette.editorSelection,
    'list.activeSelectionForeground': palette.uiForeground,
    'list.activeSelectionIconForeground': palette.uiForeground,
    'minimap.selectionHighlight': palette.uiMinimapActive,
    'panel.border': palette.uiBorder,
    'sideBar.background': palette.uiBackground,
    'sideBar.border': palette.uiBorder,
    'sideBarSectionHeader.background': palette.uiBackground,
    'sideBarSectionHeader.foreground': palette.uiForeground,
    'statusBar.background': palette.uiBackground,
    'statusBar.border': palette.uiBorder,
    'statusBar.foreground': palette.uiForegroundDim,
    'tab.activeBackground': palette.uiBackground,
    'tab.activeBorder': palette.uiBackground,
    'tab.activeBorderTop': palette.uiAccent,
    'tab.border': palette.uiBorder,
    'tab.inactiveBackground': palette.uiInputBackground,
    'tab.inactiveForeground': palette.uiForegroundDim,
    'titleBar.border': palette.uiBorder,
    'titleBar.activeBackground': palette.uiBackground,
    'titleBar.activeForeground': palette.uiForeground,
    'titleBar.inactiveBackground': palette.uiBackground,
    'titleBar.inactiveForeground': palette.uiForegroundDim,
    'input.background': palette.uiInputBackground,
    'input.foreground': palette.uiInputForeground,
    'input.border': palette.uiInputBorder,
    'terminal.ansiBlack': palette.plainText,
    'terminal.ansiRed': palette.strings,
    'terminal.ansiGreen': palette.debuggerConsolePrompt,
    'terminal.ansiYellow': palette.preprocessorStatements,
    'terminal.ansiBlue': palette.urls,
    'terminal.ansiMagenta': palette.keywords,
    'terminal.ansiCyan': palette.projectFunctionAndMethodNames,
    'terminal.ansiWhite': palette.uiBackground,
    'terminal.ansiBrightBlack': palette.uiForegroundDim,
    'terminal.ansiBrightRed': palette.strings,
    'terminal.ansiBrightGreen': palette.debuggerConsolePrompt,
    'terminal.ansiBrightYellow': palette.attributes,
    'terminal.ansiBrightBlue': palette.urls,
    'terminal.ansiBrightMagenta': palette.headings,
    'terminal.ansiBrightCyan': palette.typeDeclarations,
    'terminal.ansiBrightWhite': palette.uiBackground,
    'terminal.foreground': palette.plainText,
  },
  tokenColors: [
    {
      name: 'Plain text',
      scope: ['text', 'source', 'variable.other.readwrite', 'punctuation.definition.variable'],
      settings: { foreground: palette.plainText },
    },
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment'],
      settings: { foreground: palette.comments },
    },
    {
      name: 'Documentation',
      scope: ['comment.documentation', 'comment.block.documentation'],
      settings: { foreground: palette.documentationMarkUp },
    },
    {
      name: 'Documentation keywords',
      scope: ['comment.documentation keyword', 'comment.block.documentation storage.type'],
      settings: { foreground: palette.documentationMarkupKeywords },
    },
    {
      name: 'Strings',
      scope: ['string', 'punctuation.definition.string'],
      settings: { foreground: palette.strings },
    },
    {
      name: 'Characters and numbers',
      scope: ['constant.numeric', 'constant.character'],
      settings: { foreground: palette.characters },
    },
    {
      name: 'Regex literals',
      scope: ['string.regexp'],
      settings: { foreground: palette.regexLiterals },
    },
    {
      name: 'Keywords',
      scope: [
        'keyword',
        'keyword.operator.word',
        'keyword.operator.new',
        'storage.type',
        'storage.modifier',
        'punctuation.definition.keyword',
        'variable.language.super',
        'support.type.primitive',
      ],
      settings: { foreground: palette.keywords },
    },
    {
      name: 'Preprocessor statements',
      scope: [
        'meta.preprocessor',
        'keyword.control.directive',
        'punctuation.definition.directive',
        'entity.name.function.preprocessor',
      ],
      settings: { foreground: palette.preprocessorStatements },
    },
    {
      name: 'URLs',
      scope: ['markup.underline.link', 'string.other.link'],
      settings: { foreground: palette.urls },
    },
    {
      name: 'Attributes',
      scope: [
        'entity.other.attribute-name',
        'meta.decorator',
        'punctuation.decorator',
      ],
      settings: { foreground: palette.attributes },
    },
    {
      name: 'Type declarations',
      scope: [
        'entity.name.type',
        'entity.name.class',
        'entity.other.inherited-class',
        'support.class',
        'entity.name.struct',
      ],
      settings: { foreground: palette.typeDeclarations },
    },
    {
      name: 'Function and method declarations',
      scope: [
        'entity.name.function',
        'meta.function-call.method',
        'support.function',
        'variable.function',
      ],
      settings: { foreground: palette.otherDeclarations },
    },
    {
      name: 'Project class names',
      scope: ['support.type'],
      settings: { foreground: palette.projectClassNames },
    },
    {
      name: 'Project properties and globals',
      scope: [
        'variable.other.property',
        'variable.other.object.property',
        'meta.property.object',
      ],
      settings: { foreground: palette.projectFunctionAndMethodNames },
    },
    {
      name: 'Constants',
      scope: [
        'variable.other.constant',
        'entity.name.constant',
        'constant.language.boolean',
        'constant.language',
      ],
      settings: { foreground: palette.projectConstants },
    },
    {
      name: 'Other class names',
      scope: ['meta.function-call.constructor'],
      settings: { foreground: palette.otherClassNames },
    },
    {
      name: 'Other functions and methods',
      scope: ['support.function.builtin'],
      settings: { foreground: palette.otherFunctionAndMethodNames },
    },
    {
      name: 'Operators',
      scope: [
        'keyword.operator',
        'punctuation.accessor',
        'punctuation.definition.generic',
        'punctuation.definition.tag',
        'punctuation.separator.key-value',
      ],
      settings: { foreground: palette.plainText },
    },
    {
      name: 'Parameters',
      scope: ['variable.parameter', 'meta.function.parameters'],
      settings: { foreground: palette.projectFunctionAndMethodNames },
    },
    {
      name: 'Markup: Heading',
      scope: 'markup.heading',
      settings: { foreground: palette.headings },
    },
    {
      name: 'Markup: Strong',
      scope: 'markup.bold',
      settings: { fontStyle: 'bold' },
    },
    {
      name: 'Markup: Underline',
      scope: 'markup.underline',
      settings: { fontStyle: 'underline' },
    },
    {
      name: 'Markup Inline',
      scope: 'markup.inline.raw',
      settings: { foreground: palette.preprocessorStatements, fontStyle: '' },
    },
  ],
};
